;;; agile-gtd-rank-test.el --- Tests for agile-gtd rank functions -*- lexical-binding: t; -*-

(require 'ert)
(require 'agile-gtd)

(ert-deftest agile-gtd-prio-rank-maps-chars ()
  (should (= (agile-gtd--prio-rank ?A)  1))
  (should (= (agile-gtd--prio-rank ?B) 11))
  (should (= (agile-gtd--prio-rank ?C) 21))
  (should (= (agile-gtd--prio-rank ?D) 31))
  (should (= (agile-gtd--prio-rank ?E) 41))
  (should (= (agile-gtd--prio-rank ?F) 51))
  (should (= (agile-gtd--prio-rank ?G) 61))
  (should (= (agile-gtd--prio-rank ?H) 71))
  (should (= (agile-gtd--prio-rank ?I) 81))
  (should (null (agile-gtd--prio-rank nil))))

(ert-deftest agile-gtd-deadline-rank-maps-days ()
  (should (= (agile-gtd--deadline-rank -10) -10))
  (should (= (agile-gtd--deadline-rank  -1)  -1))
  (should (= (agile-gtd--deadline-rank   0)  -1))
  (should (= (agile-gtd--deadline-rank   1)   0))
  (should (= (agile-gtd--deadline-rank   2)   0))
  (should (= (agile-gtd--deadline-rank   3)  10))
  (should (= (agile-gtd--deadline-rank   5)  10))
  (should (= (agile-gtd--deadline-rank   6)  20))
  (should (= (agile-gtd--deadline-rank   7)  20))
  (should (= (agile-gtd--deadline-rank   8)  30))
  (should (= (agile-gtd--deadline-rank  11)  30))
  (should (= (agile-gtd--deadline-rank  12)  40))
  (should (= (agile-gtd--deadline-rank  14)  40))
  (should (= (agile-gtd--deadline-rank  15)  50))
  (should (= (agile-gtd--deadline-rank  21)  50))
  (should (= (agile-gtd--deadline-rank  22)  60))
  (should (= (agile-gtd--deadline-rank  30)  60))
  (should (= (agile-gtd--deadline-rank  31)  70))
  (should (= (agile-gtd--deadline-rank  60)  70))
  (should (= (agile-gtd--deadline-rank  61) 1000))
  (should (= (agile-gtd--deadline-rank  90) 1000)))

(ert-deftest agile-gtd-backlog-rank-cases ()
  (let ((cases '((?A  nil  nil   1)
                 (nil ?B   nil  11)
                 (?C  ?D   nil  21)
                 (?D  ?C   nil  21)
                 (nil nil  nil  45)
                 (nil ?F   nil  51)
                 (?F  ?G   nil  51)
                 (nil nil  -10 -10)
                 (nil nil    0  -1)
                 (nil nil    2   0)
                 (nil nil    3  10)
                 (?B  nil    3  10)
                 (?A  nil    3   1)
                 (nil ?A     3   1)
                 (?C  nil    3  10)
                 (nil ?C     3  10)
                 (nil nil    6  20)
                 (nil nil    8  30)
                 (nil nil   12  40)
                 (nil nil   14  40)
                 (nil nil   21  50)
                 (nil nil   30  60)
                 (nil nil   90 1000))))
    (dolist (case cases)
      (cl-destructuring-bind (prio parent-prio dl-delta expected) case
        (ert-info ((format "prio=%S parent=%S dl-delta=%S" prio parent-prio dl-delta))
          (should (= (agile-gtd--backlog-rank prio parent-prio dl-delta)
                     expected)))))))
